name: rc_car
channels:
  - defaults
  - conda
  - conda-forge
dependencies:
  - python-graphviz
  - python=3.6
  - pytest
  - pytest-cov
  - autopep8
  - bandit
  - behave=1.2.6
  - flake8
  - flask
  - requests
  - Flask-RESTful==0.3.9
  - isort
  - pylint
  - pyyaml
  - pip
  - pip:
      - freezegun
      - mock
      - numpy
      - pygame==2.1.2
      - safety
      - setuptools==65.5.1
      - -e .

variables:
  # A relevant logging level is set based on the variable ENV,
  # i.e., 'DEBUG' for 'dev' (development), 'INFO' for 'test', 'WARNING' for 'uat' (User Acceptance Testing),
  # 'ERROR' for 'prod'.
  #
  # possible values:
  # - dev: controller events, ui events, 
  # - test: sound events, notifications
  # - uat: battery events
  # - prod: car unreachable
  ENV: prod
  DEVICE_UUID: 123e4567-e89b-12d3-a456-426614174000