name: CI/CD pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: pylint analysis whilst disabling no-name-in-module, no-member, and protected-access to avoid false positives
      run: |
        pylint --extension-pkg-whitelist=pygame $(git ls-files '*.py') --disable=W0212
    - name: Run unit tests via pytest
      run: |
        pytest --cov-report term-missing --cov=rc_car --cov-config=.coveragerc tests
    - name: Run cucumber
      run: |
        behave
    - name: Run bandit for the first security scan
      run: |
        bandit --ini .bandit
    - name: Run safety for the second (complementary) security scan
      run: |
        safety check